dist: xenial
language: python
python:
  - "3.10"
  - "3.11"
  - "3.12"

matrix:
  allow_failures:
    python: "nightly"

install:
  - pip install poetry
  - poetry install

script:
  - poetry run pytest -v
